version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: app_modproj
    hostname: mod
    env_file:
      - .env
    ports:
      - "${HOST_PORT_HOSPEDEIRO}:${HOST_PORT_CONTAINER}" # Mapeia a porta do contêiner para a porta definida em HOST_PORT
    volumes:
      - .:/app

    environment:
      HOST: "0.0.0.0" # Define o host do servidor Vite para que seja acessível em todas as interfaces de rede
    # command: yarn
    